(function(_ds){var window=this;var hEa=function(){return(0,_ds.P)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},iEa=function(){return(0,_ds.P)('<div class="devsite-book-nav-blur"></div>')},jEa=function(a){a=a.dN;a=_ds.XI(new _ds.Rt("{NUMBER_OF_MATCHING_DESCENDANTS,plural, =1{{XXX_1}\u00a0coincidencia}other{{XXX_2}\u00a0coincidencias}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.Bw(_ds.us(1)),XXX_2:_ds.Bw(_ds.us(a))});return(0,_ds.P)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var kEa="onpointerover"in window?"pointerover":"mouseover",HT=function(a){var b=a.querySelectorAll(".devsite-nav-item").length>0,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.Dk(a,"visually-hidden","",c))},lEa=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight,c=b?document.documentElement.scrollTop/b:0;a.eventHandler.Mb(a,
_ds.Il,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.ea.removeAttribute("animatable")});_ds.Dk(a,"animatable","");b=_ds.Vf(a.oa`animatable`);b(a.background,"animatable","");b(a.ea,"animatable","");a.hasAttribute("collapsed")?(_ds.Dk(a,"aria-label","Ocultar panel de navegaci\u00f3n lateral",a.j),_ds.Dk(a,"data-title","Ocultar panel de navegaci\u00f3n lateral",a.j),a.removeAttribute("collapsed"),_ds.Kt(a.j,"expanded","true"),IT(a,"expandedLeftNav","Expanded book nav",
"click")):(_ds.Dk(a,"aria-label","Mostrar panel de navegaci\u00f3n lateral",a.j),_ds.Dk(a,"data-title","Mostrar panel de navegaci\u00f3n lateral",a.j),_ds.Dk(a,"collapsed",""),_ds.Kt(a.j,"expanded","false"),IT(a,"collapsedLeftNav","Collapsed book nav","click"),a.eventHandler.Mb(a,_ds.Il,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.hm();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},mEa=function(a){a.eventHandler.listen(a,
"click",b=>{var c=JT(a,b.target);c&&IT(a,"click",`Book nav link, pathname: ${c.href}`,void 0,{eventDetail:c.href});KT(a,b)});a.eventHandler.listen(a,"keypress",b=>{b.key==="Enter"&&KT(a,b)});a.eventHandler.listen(a,[kEa,"focusin"],b=>{b.defaultPrevented||(b=JT(a,b.target))&&_ds.Lf(b,_ds.bm(b.href).href)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.o&&(LT(a,"_book")?a.removeAttribute("top-level-nav"):_ds.Dk(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",
()=>void a.va.cb());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.va.cb()});a.eventHandler.listen(a,"scroll",()=>{_ds.Dk(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",()=>{a.Fa.cb()});a.m&&(a.eventHandler.listen(a.m,"keyup",()=>void a.Aa.cb()),a.eventHandler.listen(a.m,"focus",()=>void MT(a,"focus")));a.ra&&a.eventHandler.listen(a.ra,["click","keydown"],b=>{if(b.type==="click"||b.key==="Enter"||b.key==="Escape"){a.m&&(a.m.value="",a.m.focus());let c;(c=a.ra)==null||c.classList.add("hidden");
NT(a);OT(a);MT(a,b.type)}})},PT=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.qa=new Set(b);if(!_ds.F().hash&&c)nEa(a,a.qa);else{c=new _ds.sM;for(let d of a.qa)_ds.rM(c,d)}},QT=async function(a){var b=await _ds.x();for(let c of a.qa)b.unregisterIntersectionForElement(c)},JT=function(a,b){b=_ds.El(b,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0);return b===a?null:b},IT=function(a,b,c,d,e){a.Da(Object.assign({},{category:"Site-Wide Custom Events",
action:d||b},c&&{label:c}));b=Object.assign({},{type:"bookNav",name:b},e&&{metadata:e});a.dispatchEvent(_ds.rf(b))},KT=function(a,b){if(!b.defaultPrevented){var c=b.target;c.getAttribute("id")==="devsite-close-nav"&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.Dk(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&LT(a,d)&&(b.preventDefault(),b.stopPropagation(),
a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!((g=f)==null?0:(h=g.closest(".devsite-nav-title"))==null?0:h.hasAttribute("href"))){for(b=b.type==="click"||b.type==="touchend";f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&
_ds.Dk(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.o&&(d=a.o.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},MT=function(a,b){IT(a,b==="focus"?"filterInput":"filterClearButton",b==="focus"?"devsite-book-nav-filter input":
"devsite-book-nav-filter filter-clear-button",b)},RT=function(a){a.xa=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},TT=function(a){var b=_ds.F().searchParams.get("nf");a.m&&b&&(a.m.value=b,ST(a))},ST=function(a){if(a.xa.length){NT(a);OT(a);var b,c,d=(b=a.m)==null?void 0:(c=b.value)==null?void 0:c.trim().toLowerCase();if(d){var e;(e=a.ra)==null||e.classList.remove("hidden");for(let g of a.xa){var f=g.querySelectorAll(".devsite-nav-text");
a=g.classList.contains("devsite-nav-expandable");e=c=!1;b=0;let h,k,l,m=((l=(h=g)==null?void 0:(k=h.getAttribute("data-synonyms"))==null?void 0:k.split(","))!=null?l:[]).some(q=>q.toLowerCase().includes(d)),n,p;if(d&&a&&(m||((n=g.querySelector(".devsite-nav-text"))==null?0:(p=n.textContent)==null?0:p.toLowerCase().includes(d))))e=c=!0;else for(let q of f){let t,w,y,H;f=((H=(t=q)==null?void 0:(w=t.parentElement)==null?void 0:(y=w.getAttribute("data-synonyms"))==null?void 0:y.split(","))!=null?H:[]).some(G=>
G.toLowerCase().includes(d));if(d){let G;if(f||((G=q.textContent)==null?0:G.toLowerCase().includes(d)))c=!0,++b}}if(c===!0){g.classList.remove("hidden");if(e){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(let q of c){q.classList.remove("hidden");let t,w,y,H;c=((H=(t=q)==null?void 0:(w=t.parentElement)==null?void 0:(y=w.getAttribute("data-synonyms"))==null?void 0:y.split(","))!=null?H:[]).some(J=>J.toLowerCase().includes(d));let G;d&&(c||((G=q.textContent)==null?0:G.toLowerCase().includes(d)))&&
++b}}oEa(g,d)}a&&b>0&&pEa(g,b)}}else(f=a.ra)==null||f.classList.add("hidden")}},NT=function(a){for(let b of a.xa){let c;b.classList.toggle("hidden",!((c=a.m)==null||!c.value))}},OT=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(let c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(let c of a)a=c.parentElement,b=a==null?void 0:a.textContent,a&&b&&_ds.Tf(a,_ds.pg(b))}},oEa=function(a,b){if(a=
a.querySelector(".devsite-nav-text")){var c,d=(c=a.textContent)==null?void 0:c.replace(new RegExp(`(${b})`,"ig"),"<mark>$1</mark>");d&&_ds.Tf(a,_ds.pg(d))}},pEa=function(a,b){if(a=a.querySelector(".devsite-nav-text"))b=_ds.xq(jEa,{dN:b}),a.appendChild(b)},nEa=async function(a,b){if(a.connected){var c=await _ds.x(),d=new _ds.sM,e=f=>{f=f.target;_ds.rM(d,f);a.qa.delete(f);c.unregisterIntersectionForElement(f)};for(let f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},LT=function(a,
b){var c=!1;if(a.o)for(let d of a.o.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.Dk(a,"hidden","",d);return c},UT=function(a,b=a){b||(b=a);for(let c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active"),c.removeAttribute("aria-current");a=_ds.mm(_ds.F().pathname);a=`[href="${_ds.bm(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(let c of b.querySelectorAll(a))c.classList.add("devsite-nav-active"),_ds.Kt(c,"current","page")},VT=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},qEa=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.hm(),await WT(a),await a.ya,
await _ds.x(),await _ds.hm(),await WT(a))},WT=async function(a){if(a.connected&&a.o){await _ds.x();var b=a.o.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await rEa(a,b))}},rEa=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Rn(b,a,!0).y;await _ds.hm();c&&_ds.Dk(a,"user-scrolled","")}},XT=class extends _ds.Gk{static get observedAttributes(){return["collapsed","fixed","hidden"]}constructor(){super();this.connected=!1;this.ra=this.m=
this.ua=this.o=null;this.xa=[];this.eventHandler=new _ds.v;this.Ba=()=>{};this.qa=new Set;_ds.Ck(this,this.oa`animatable`,this.oa`aria-expanded`,this.oa`aria-label`,this.oa`collapsed`,this.oa`data-title`,this.oa`fixed`,this.oa`has-book-nav`,this.oa`hidden`,this.oa`top-level-nav`,this.oa`user-scrolled`,this.oa`visually-hidden`);this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.j=_ds.xq(hEa);this.ea=_ds.xq(iEa);this.ya=new Promise(a=>{this.Ba=a});
this.va=new _ds.xh(()=>{this.connected&&HT(this)},20);this.Aa=new _ds.xh(()=>{ST(this)},20);this.Fa=new _ds.xh(()=>{lEa(this)},100)}async connectedCallback(){this.connected=!0;_ds.ml(this.background,this);this.hasAttribute("hidden")&&(_ds.Dk(this,"hidden","",this.j),_ds.Dk(this,"hidden","",this.ea));var a;(a=this.parentElement)==null||a.insertBefore(this.j,this.nextSibling);_ds.Dk(this,"aria-label","Ocultar panel de navegaci\u00f3n lateral",this.j);_ds.Dk(this,"data-title","Ocultar panel de navegaci\u00f3n lateral",
this.j);_ds.Dk(this,"aria-expanded","true",this.j);var b;(b=this.parentElement)==null||b.insertBefore(this.ea,this.nextSibling);if(this.ua=this.querySelector(".devsite-book-nav-filter"))this.m=this.ua.querySelector("input[type=text]"),this.ra=this.ua.querySelector(".filter-clear-button"),RT(this),TT(this);HT(this);mEa(this);await this.init();PT(this)}disconnectedCallback(){this.connected=!1;this.eventHandler.removeAll();QT(this);this.qa.clear();var a=document.querySelector("#devsite-hamburger-menu");
a&&_ds.Dk(this,"visually-hidden","",a);a=[this.background,this.j,this.ea];for(let b of a)b&&_ds.ol(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.ea.removeAttribute("animatable");this.ea.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){a==="hidden"&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if(a==="hidden"||a==="collapsed"){var b=
document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.Dk(this,"has-book-nav","",b))}if(a==="fixed"||a==="hidden"||a==="collapsed"){b=this.hasAttribute(a);let c=[this.background,this.j,this.ea];for(let d of c)d&&(b?_ds.Dk(this,a,"",d):d.removeAttribute(a))}a==="fixed"&&this.Ba()}async init(a=!0){if(this.connected){this.ea.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);
this.o=this.querySelector(".devsite-mobile-nav-bottom");_ds.Dk(this,"top-level-nav","");this.o&&this.o.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");this.children.length===0&&_ds.Dk(this,"hidden","");if(this.background)for(let b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.Dk(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(UT(this),VT(this),await qEa(this)):(await _ds.hm(),await WT(this))}}async wd(a){a?(a=a.querySelector("nav")||null,UT(this,a),VT(this,
a),a&&(await QT(this),this.qa.clear(),PT(this,a,!1)),_ds.Fk(this,this.querySelector("nav"),a)):_ds.ll(this);RT(this);if(this.m){this.m.value="";let b;(b=this.ra)==null||b.classList.add("hidden");TT(this)}await _ds.hm();await this.init(!1)}};XT.prototype.updateContent=XT.prototype.wd;XT.prototype.attributeChangedCallback=XT.prototype.attributeChangedCallback;XT.prototype.disconnectedCallback=XT.prototype.disconnectedCallback;XT.prototype.connectedCallback=XT.prototype.connectedCallback;try{customElements.define("devsite-book-nav",XT)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
