(function(_ds){var window=this;var VTa=function(a){var b=a.qP,c=a.wf,d=a.oJ;a=a.tM;var e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle"><span class="devsite-nav-title" role="heading" aria-level="2"><span class="devsite-nav-text">En esta p\u00e1gina</span></span>';c&&(e=e+'<button type="button" title="'+_ds.Fw("Expandir o contraer contenido"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";var f=b.length;for(let h=0;h<f;h++){var g=b[h];
e+='<li class="devsite-nav-item"'+(c&&g.index<a?" visible":"")+'><a href="#'+_ds.U(g.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.U(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.U(h)+'" track-metadata-link-destination="#'+_ds.U(g.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.T(g.text)+"</span></a>";if(g.children.length){e+=
'<ul class="devsite-nav-list">';g=g.children;let k=g.length;for(let l=0;l<k;l++){let m=g[l];e+='<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.U(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.U(h)+"."+_ds.U(l)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.U(h)+"."+_ds.U(l)+'" track-metadata-link-destination="#'+
_ds.U(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.T(m.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Probar</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Pru\u00e9balo</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.Fw("Expandir o contraer contenido"),e+='"></button></li>');return(0,_ds.P)(e+"</ul>")};var W2=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.wf?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),WTa(a,b),a.ua=!0):a.hide()}},YTa=async function(a){await XTa(a);if(a.j){var b=`#${a.j.id}`,c=encodeURI(b);b=a.qa.get(b)||a.qa.get(c);a.o!==b&&(a.o&&a.o.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.ra&&("scrollIntoViewIfNeeded"in b?b.scrollIntoViewIfNeeded():b.scrollIntoView()),
a.o=b))}},ZTa=function(a){a.wf||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),()=>{a.Aa.cb()});a.eventHandler.listen(document.body,"devsite-content-updated",()=>{W2(a)})},$Ta=async function(a){if("IntersectionObserver"in _ds.ag()){a.kd&&a.kd.disconnect();var b=document.querySelector("devsite-header");let c=152;b&&(await customElements.whenDefined("devsite-header"),
(b=b.va())&&(c=b));a.kd=new IntersectionObserver(d=>{for(let e of d)e.isIntersecting?a.ea.add(e.target):a.ea.delete(e.target);a.Aa.cb()},{rootMargin:`${c}px 0px 0px 0px`,threshold:[0,1]})}a.Ba.resolve()},XTa=async function(a){var b=0,c=document.querySelector("devsite-header");c&&(await customElements.whenDefined("devsite-header"),b=c.qa());c=a.m.findIndex(e=>a.ea.has(e)&&e.getBoundingClientRect().top>=b);var d=a.m[c];if(d){let e=await aUa();d.getBoundingClientRect().top-b>e&&c>0?a.j=a.m[c-1]:a.j=
d}else a.j&&a.j.getBoundingClientRect().top>window.innerHeight&&(c=a.m.indexOf(a.j),c>0&&(a.j=a.m[c-1]))},WTa=function(a,b){var c=[],d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.m=[...b.querySelectorAll(e)].filter(f=>f.id&&f.dataset.text).filter(f=>{var g=[document.body.hasAttribute("free-trial")?
".ineligible":".eligible",".ds-selector-tabs,.kd-tabbed-horz,devsite-selector,.devsite-dialog"].join();return f.closest(g)?!1:!0});for(let [f,g]of a.m.entries())b=g,b={id:b.id,level:b.tagName.toLowerCase(),text:b.dataset.text,children:[],index:f},b.level==="h2"?(c.push(b),d=!0):d?c[c.length-1].children.push(b):c.push(b);_ds.yb(a.xa,c,a.va.bind(a))&&a.ua||(c.length?(bUa(a,c),a.show(),a.wf||cUa(a)):a.hide(),a.xa=c)},bUa=function(a,b){var c=_ds.xq(VTa,{qP:b,wf:a.wf,oJ:!!document.body.querySelector("devsite-apix, .devsite-apix"),
tM:b.length<8?8:5});if(a.ra)(b=c.querySelector("button.devsite-show-apix"))&&a.eventHandler.listen(b,"click",()=>{a.dispatchEvent(new CustomEvent("devsite-concierge-open-panel",{bubbles:!0,composed:!0,detail:{Sy:"devsite-concierge-api-explorer-panel"}}))});else{b=document.querySelector("button.devsite-show-apix");let e=document.querySelector("devsite-apix");var d=!(e==null?0:e.querySelector("div.devsite-apix"));b&&e&&d&&a.eventHandler.listen(b,"click",()=>{e.scrollIntoView()})}b=c.querySelectorAll("a.devsite-nav-title");
for(let e of b){b=e;d=b.hash;let f=encodeURI(b.hash);a.qa.set(d,b);a.qa.set(f,b)}_ds.ll(a);a.wf&&_ds.Dk(a,"hidden","",c);a.appendChild(c);if(a.wf){if(a.getElementsByClassName("devsite-nav-item").length>8){for(let e of a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"))a.eventHandler.listen(e,"click",()=>{a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.Dk(a,"expanded","")});_ds.Dk(a,"expandable","")}else a.removeAttribute("expandable");setTimeout(()=>{c.removeAttribute("hidden")},
0)}},cUa=async function(a){await a.Ba.promise;if(a.kd){a.kd.disconnect();a.ea.clear();a.o&&a.o.classList.remove("devsite-nav-active");a.o=null;for(let b of a.m)a.kd.observe(b)}},aUa=async function(){var a=0,b=0,c=document.querySelector("devsite-header");c&&(await customElements.whenDefined("devsite-header"),a=c.qa(),b=c.va());return Math.max(b-a,Math.floor((window.innerHeight-a)/5))},X2=class extends _ds.Gk{static get observedAttributes(){return["max-height","offset"]}constructor(){super();this.eventHandler=
new _ds.v;this.Ba=new _ds.gh;this.ea=new Set;this.qa=new Map;this.ya=new _ds.xh(()=>void W2(this),16);this.Aa=new _ds.xh(()=>void YTa(this),33);this.j=this.o=null;this.m=[];this.ua=!1;this.kd=null;this.ra=this.wf=!1;this.xa=[];_ds.Ck(this,(0,_ds.dg)`disabled`,(0,_ds.dg)`has-sidebar`,(0,_ds.dg)`hidden`,(0,_ds.dg)`expandable`,(0,_ds.dg)`expanded`,(0,_ds.dg)`visible`)}connectedCallback(){this.wf=this.hasAttribute("devsite-toc-embedded");this.ra=document.body.hasAttribute("concierge");W2(this);ZTa(this)}disconnectedCallback(){this.hide();
this.ua=!1;this.eventHandler.removeAll()}vt(a){a=a&&a.toLowerCase()==="false";this.xa=[];_ds.ll(this);a?(_ds.Dk(this,"disabled",""),this.hide()):(this.removeAttribute("disabled"),this.ya.cb())}hide(){_ds.ll(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.Dk(this,"hidden","");if(!this.wf){let a=document.querySelector(".devsite-sidebar"),b=document.querySelector(".devsite-main-content");(a==null?0:a.contains(this))&&b&&b.removeAttribute("has-sidebar")}}show(){this.dispatchEvent(new CustomEvent("devsite-element-visible",
{bubbles:!0}));this.removeAttribute("hidden");_ds.Dk(this,"visible","");if(!this.wf){let a=document.querySelector(".devsite-sidebar"),b=document.querySelector(".devsite-main-content");(a==null?0:a.contains(this))&&b&&_ds.Dk(this,"has-sidebar","",b);$Ta(this)}}va(a,b){var c=!0;if(a.children.length||b.children.length)c=_ds.yb(a.children,b.children,this.va.bind(this));return c&&a.id===b.id&&a.text===b.text}};X2.prototype.renderUpdatedContent=X2.prototype.vt;X2.prototype.disconnectedCallback=X2.prototype.disconnectedCallback;
X2.prototype.connectedCallback=X2.prototype.connectedCallback;try{customElements.define("devsite-toc",X2)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
