(function(_ds){var window=this;var VX=function(a,b){_ds.Fn(a,"transform","translate3d("+b+"px,0px,0px)")};var YX=function(a){a.o=WX(a,".devsite-top-logo-row-wrapper-wrapper");a.j=WX(a,".devsite-collapsible-section");a.ea=WX(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.o}`);a.setAttribute("bottom-row--height",`${a.j}`);a.setAttribute("bottom-tabs--height",`${a.ea}`);a.style.setProperty("--devsite-js-top-row--height",`${a.o}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.j}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.ea}px`);XX(a);a.m.resolve()},
XX=function(a){var b=a.querySelector(".devsite-collapsible-section");a.offset>=a.j&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.j-a.ea&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.Ba&&(_ds.Fn(b,"transform",`translate3d(0, -${a.offset}px, 0)`),ZX(a),a.Ba=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.qa()}px`)},JIa=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),
c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){a.xa.removeAll();a.ra&&window.cancelAnimationFrame(a.ra);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.Ag(b.offsetWidth,b.offsetHeight);b=new _ds.Ag(c.offsetWidth,c.offsetHeight);var f=_ds.ao(c,"margin"),g=document.documentElement.getAttribute("dir")==="rtl"?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?
e:0,l=f?h:1;_ds.Fn(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});VX(c,a.hasAttribute("search-active")?0:e);a.xa.Mb(d,_ds.Il,()=>{var m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),VX(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.ra=window.requestAnimationFrame(()=>{c.setAttribute("transition","");_ds.Fn(d,"transform","scale3d("+
l+",1,1)");VX(c,k)})}},KIa=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=a==null?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.hm(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===
d&&e.focus(),c.setAttribute("disabled","")))}},LIa=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.getBrowserEvent();_ds.Fl(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{document.body.removeAttribute("devsite-book-nav--open")});a.eventHandler.listen(window,"resize",()=>{$X(a)});a.eventHandler.listen(document.body,["devsite-page-loaded",
"devsite-content-updated"],()=>{$X(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||b.target.getAttribute("id")!=="devsite-hamburger-menu"||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},aY=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){let b=document.createElement("div");b.classList.add("devsite-search-background");
b.style.opacity="1";a.appendChild(b)}},ZX=function(a){a.j===0?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},$X=function(a){window.requestAnimationFrame(()=>{a.Aa.cb()})},WX=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},bY=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=
0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},cY=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Fk(a,c,b))},MIa=function(a,b){var c=a.querySelectorAll(".devsite-header-link"),d=b.querySelectorAll(".devsite-header-link");b=a.querySelector("devsite-language-selector");var e=a.querySelector("devsite-user");d.length>0&&(d=[...d],b?(a.updated=!0,b.after(...d)):e&&(a.updated=!0,e.before(...d)));c.length>0&&(a.updated=!0,c.forEach(f=>
{f.remove()}))},NIa=class extends _ds.Gk{constructor(){super(...arguments);this.eventHandler=new _ds.v;this.Ba=-1;this.xa=new _ds.v;this.ra=0;this.ua=new MutationObserver(()=>{YX(this)});this.Aa=new _ds.xh(()=>{YX(this);ZX(this)},15);this.authUser=void 0;this.offset=this.ea=this.j=this.o=0;this.updated=!1;this.m=new _ds.gh}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||
"")||0;XX(this);break;case "search-active":JIa(this);break;case "bottom-row--hidden":a=c!==null,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),KIa(this,a)}}connectedCallback(){LIa(this);aY(this);ZX(this);YX(this);this.ua.observe(this,{childList:!0,subtree:!0});XX(this);var a=_ds.F();this.authUser=_ds.Ol(_ds.Pl(a.href),"authuser")}disconnectedCallback(){this.eventHandler.removeAll();
this.ua.disconnect()}qa(){return this.o+this.j-this.offset}va(){return this.o+this.j}wd(a){this.m&&this.m.resolve();this.m=new _ds.gh;this.updated=!1;if(a){cY(this,a,".devsite-header-upper-tabs");cY(this,a,".devsite-collapsible-section");cY(this,a,".devsite-product-name-wrapper");cY(this,a,"devsite-language-selector");cY(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&bY(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");
c&&b&&(bY(c,b),c=_ds.F(),c=_ds.Ol(_ds.Pl(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Fk(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));MIa(this,a)}!this.updated&&a&&(_ds.ll(this),this.appendChild(a));aY(this);$X(this)}async ready(){return this.m.promise}};try{customElements.define("devsite-header",NIa)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
