(function(_ds){var window=this;var ira=function(){return(0,_ds.S)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},jra=function(){return(0,_ds.S)('<div class="devsite-book-nav-blur"></div>')},kra=function(a){a=a.yC;a=_ds.BQ(new _ds.jz("{NUMBER_OF_MATCHING_DESCENDANTS,plural, =1{{XXX_1}\u00a0coincidencia}other{{XXX_2}\u00a0coincidencias}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.eL(_ds.wx(1)),XXX_2:_ds.eL(_ds.wx(a))});return(0,_ds.S)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var lra="onpointerover"in window?"pointerover":"mouseover",u_=function(a){var b=a.querySelectorAll(".devsite-nav-item").length>0,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.gn(a,"visually-hidden","",c))},mra=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight,c=b?document.documentElement.scrollTop/b:0;_ds.Aq(a.eventHandler,
a,_ds.oo,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.ea.removeAttribute("animatable")});_ds.gn(a,"animatable","");b=_ds.Dg(a.ma`animatable`);b(a.background,"animatable","");b(a.ea,"animatable","");a.hasAttribute("collapsed")?(_ds.gn(a,"aria-label","Ocultar panel de navegaci\u00f3n lateral",a.j),_ds.gn(a,"data-title","Ocultar panel de navegaci\u00f3n lateral",a.j),a.removeAttribute("collapsed"),_ds.$y(a.j,"expanded","true"),v_(a,"expandedLeftNav","Expanded book nav",
"click")):(_ds.gn(a,"aria-label","Mostrar panel de navegaci\u00f3n lateral",a.j),_ds.gn(a,"data-title","Mostrar panel de navegaci\u00f3n lateral",a.j),_ds.gn(a,"collapsed",""),_ds.$y(a.j,"expanded","false"),v_(a,"collapsedLeftNav","Collapsed book nav","click"),_ds.Aq(a.eventHandler,a,_ds.oo,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.Zo();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},nra=function(a){a.eventHandler.listen(a,
"click",b=>{var c=w_(a,b.target);c&&v_(a,"click",`Book nav link, pathname: ${c.href}`,void 0,{eventDetail:c.href});x_(a,b)});a.eventHandler.listen(a,"keypress",b=>{b.key==="Enter"&&x_(a,b)});a.eventHandler.listen(a,[lra,"focusin"],b=>{b.defaultPrevented||(b=w_(a,b.target))&&_ds.tg(b,_ds.So(b.href).href)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.o&&(y_(a,"_book")?a.removeAttribute("top-level-nav"):_ds.gn(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",
()=>void a.xa.Ra());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.xa.Ra()});a.eventHandler.listen(a,"scroll",()=>{_ds.gn(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",()=>{a.Ea.Ra()});a.m&&(a.eventHandler.listen(a.m,"keyup",()=>void a.ya.Ra()),a.eventHandler.listen(a.m,"focus",()=>void z_(a,"focus")));a.qa&&a.eventHandler.listen(a.qa,["click","keydown"],b=>{if(b.type==="click"||b.key==="Enter"||b.key==="Escape"){a.m&&(a.m.value="",a.m.focus());let c;(c=a.qa)==null||c.classList.add("hidden");
A_(a);B_(a);z_(a,b.type)}})},C_=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.oa=new Set(b);if(!_ds.D().hash&&c)ora(a,a.oa);else{c=new _ds.jU;for(let d of a.oa)_ds.iU(c,d)}},D_=async function(a){var b=await _ds.v();for(let c of a.oa)b.unregisterIntersectionForElement(c)},w_=function(a,b){b=_ds.ko(b,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0);return b===a?null:b},v_=function(a,b,c,d,e){a.Ca(Object.assign({},{category:"Site-Wide Custom Events",
action:d||b},c&&{label:c}));b=Object.assign({},{type:"bookNav",name:b},e&&{metadata:e});a.dispatchEvent(_ds.Yf(b))},x_=function(a,b){if(!b.defaultPrevented){var c=b.target;c.getAttribute("id")==="devsite-close-nav"&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.gn(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&y_(a,d)&&(b.preventDefault(),b.stopPropagation(),
a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!((g=f)==null?0:(h=g.closest(".devsite-nav-title"))==null?0:h.hasAttribute("href"))){for(b=b.type==="click"||b.type==="touchend";f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&
_ds.gn(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.o&&(d=a.o.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},z_=function(a,b){v_(a,b==="focus"?"filterInput":"filterClearButton",b==="focus"?"devsite-book-nav-filter input":
"devsite-book-nav-filter filter-clear-button",b)},E_=function(a){a.ua=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},G_=function(a){var b=_ds.D().searchParams.get("nf");a.m&&b&&(a.m.value=b,F_(a))},F_=function(a){if(a.ua.length){A_(a);B_(a);var b,c,d=(b=a.m)==null?void 0:(c=b.value)==null?void 0:c.trim().toLowerCase();if(d){var e;(e=a.qa)==null||e.classList.remove("hidden");for(let g of a.ua){var f=g.querySelectorAll(".devsite-nav-text");
a=g.classList.contains("devsite-nav-expandable");e=c=!1;b=0;let h,k,l,m=((l=(h=g)==null?void 0:(k=h.getAttribute("data-synonyms"))==null?void 0:k.split(","))!=null?l:[]).some(r=>r.toLowerCase().includes(d)),n,q;if(d&&a&&(m||((n=g.querySelector(".devsite-nav-text"))==null?0:(q=n.textContent)==null?0:q.toLowerCase().includes(d))))e=c=!0;else for(let r of f){let B,F,I,Q;f=((Q=(B=r)==null?void 0:(F=B.parentElement)==null?void 0:(I=F.getAttribute("data-synonyms"))==null?void 0:I.split(","))!=null?Q:[]).some(R=>
R.toLowerCase().includes(d));if(d){let R;if(f||((R=r.textContent)==null?0:R.toLowerCase().includes(d)))c=!0,++b}}if(c===!0){g.classList.remove("hidden");if(e){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(let r of c){r.classList.remove("hidden");let B,F,I,Q;c=((Q=(B=r)==null?void 0:(F=B.parentElement)==null?void 0:(I=F.getAttribute("data-synonyms"))==null?void 0:I.split(","))!=null?Q:[]).some(M=>M.toLowerCase().includes(d));let R;d&&(c||((R=r.textContent)==null?0:R.toLowerCase().includes(d)))&&
++b}}pra(g,d)}a&&b>0&&qra(g,b)}}else(f=a.qa)==null||f.classList.add("hidden")}},A_=function(a){for(let b of a.ua){let c;b.classList.toggle("hidden",!((c=a.m)==null||!c.value))}},B_=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(let c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(let c of a)a=c.parentElement,b=a==null?void 0:a.textContent,a&&b&&_ds.Bg(a,_ds.dh(b))}},pra=function(a,b){if(a=
a.querySelector(".devsite-nav-text")){var c,d=(c=a.textContent)==null?void 0:c.replace(new RegExp(`(${b})`,"ig"),"<mark>$1</mark>");d&&_ds.Bg(a,_ds.dh(d))}},qra=function(a,b){if(a=a.querySelector(".devsite-nav-text"))b=_ds.Ju(kra,{yC:b}),a.appendChild(b)},ora=async function(a,b){if(a.connected){var c=await _ds.v(),d=new _ds.jU,e=f=>{f=f.target;_ds.iU(d,f);a.oa.delete(f);c.unregisterIntersectionForElement(f)};for(let f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},y_=function(a,
b){var c=!1;if(a.o)for(let d of a.o.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.gn(a,"hidden","",d);return c},H_=function(a,b=a){b||(b=a);for(let c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active"),c.removeAttribute("aria-current");a=_ds.fp(_ds.D().pathname);a=`[href="${_ds.So(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(let c of b.querySelectorAll(a))c.classList.add("devsite-nav-active"),_ds.$y(c,"current","page")},I_=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},rra=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.Zo(),await J_(a),await a.Ba,
await _ds.v(),await _ds.Zo(),await J_(a))},J_=async function(a){if(a.connected&&a.o){await _ds.v();var b=a.o.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await sra(a,b))}},sra=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Nq(b,a,!0).y;await _ds.Zo();c&&_ds.gn(a,"user-scrolled","")}},K_=class extends _ds.kn{static get observedAttributes(){return["collapsed","fixed","hidden"]}constructor(){super();this.connected=!1;this.qa=this.m=
this.ra=this.o=null;this.ua=[];this.eventHandler=new _ds.u;this.va=()=>{};this.oa=new Set;_ds.fn(this,this.ma`animatable`,this.ma`aria-expanded`,this.ma`aria-label`,this.ma`collapsed`,this.ma`data-title`,this.ma`fixed`,this.ma`has-book-nav`,this.ma`hidden`,this.ma`top-level-nav`,this.ma`user-scrolled`,this.ma`visually-hidden`);this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.j=_ds.Ju(ira);this.ea=_ds.Ju(jra);this.Ba=new Promise(a=>{this.va=a});
this.xa=new _ds.ji(()=>{this.connected&&u_(this)},20);this.ya=new _ds.ji(()=>{F_(this)},20);this.Ea=new _ds.ji(()=>{mra(this)},100)}async connectedCallback(){this.connected=!0;_ds.Un(this.background,this);this.hasAttribute("hidden")&&(_ds.gn(this,"hidden","",this.j),_ds.gn(this,"hidden","",this.ea));var a;(a=this.parentElement)==null||a.insertBefore(this.j,this.nextSibling);_ds.gn(this,"aria-label","Ocultar panel de navegaci\u00f3n lateral",this.j);_ds.gn(this,"data-title","Ocultar panel de navegaci\u00f3n lateral",
this.j);_ds.gn(this,"aria-expanded","true",this.j);var b;(b=this.parentElement)==null||b.insertBefore(this.ea,this.nextSibling);if(this.ra=this.querySelector(".devsite-book-nav-filter"))this.m=this.ra.querySelector("input[type=text]"),this.qa=this.ra.querySelector(".filter-clear-button"),E_(this),G_(this);u_(this);nra(this);await this.init();C_(this)}disconnectedCallback(){this.connected=!1;_ds.E(this.eventHandler);D_(this);this.oa.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&
_ds.gn(this,"visually-hidden","",a);a=[this.background,this.j,this.ea];for(let b of a)b&&_ds.Wn(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.ea.removeAttribute("animatable");this.ea.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){a==="hidden"&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if(a==="hidden"||a==="collapsed"){var b=document.querySelector(".devsite-main-content");
b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.gn(this,"has-book-nav","",b))}if(a==="fixed"||a==="hidden"||a==="collapsed"){b=this.hasAttribute(a);let c=[this.background,this.j,this.ea];for(let d of c)d&&(b?_ds.gn(this,a,"",d):d.removeAttribute(a))}a==="fixed"&&this.va()}async init(a=!0){if(this.connected){this.ea.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.o=this.querySelector(".devsite-mobile-nav-bottom");
_ds.gn(this,"top-level-nav","");this.o&&this.o.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");this.children.length===0&&_ds.gn(this,"hidden","");if(this.background)for(let b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.gn(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(H_(this),I_(this),await rra(this)):(await _ds.Zo(),await J_(this))}}async ec(a){a?(a=a.querySelector("nav")||null,H_(this,a),I_(this,a),a&&(await D_(this),this.oa.clear(),C_(this,a,!1)),
_ds.jn(this,this.querySelector("nav"),a)):_ds.Tn(this);E_(this);if(this.m){this.m.value="";let b;(b=this.qa)==null||b.classList.add("hidden");G_(this)}await _ds.Zo();await this.init(!1)}};K_.prototype.updateContent=K_.prototype.ec;K_.prototype.attributeChangedCallback=K_.prototype.attributeChangedCallback;K_.prototype.disconnectedCallback=K_.prototype.disconnectedCallback;K_.prototype.connectedCallback=K_.prototype.connectedCallback;try{customElements.define("devsite-book-nav",K_)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
